### PR TITLE
Examples folder

### PR DESCRIPTION
**Pull request by mysteryDate**
Just a couple of examples showing how to write a basic frag shader, load textures and use the global uniforms.

### CODE REVIEW

**Comment by fordhurley** [comment]
Great idea! These will be very useful for testing this package, too. 

Love the YCgCo one! Any idea why that's typically written YCoCg? YCgCo makes so much more sense...

**Comment by mysteryDate** [comment]
You're officially way too nice to me. `YCgCo` was a typo...

**Comment by mysteryDate** [comment]
Why does `YCgCo` make more sense?

**Comment by mysteryDate** [comment]
Ah, I see, with the way the matrix is constructed `YCgCo` *does* make more sense, that's probably why I put it in that order.

**Comment by fordhurley** [comment]
Exactly, the matrix order!

**Pull request merged**
